package constants

const ModuleName = "module"
const ModuleAlias = "m"
const ModuleUsage = "signal cli to create a template for a WASM module; value will be used to name the module"
const LanguageName = "language"
const LanguageAlias = "l"
const LanguageUsage = "the language you want to create your new wyvrn app/module for; apps can run modules compiled from multiple languages, but needs a language to make the first module with"
const DirectoryName = "dir"
const DirectoryAlias = "d"
const DirectoryUsage = "specify the directory to create your new wyvrn app/module; defaults to the current directory"
const DevName = "dev"
const DevAlias = "d"
const DevUsage = "specify to run wyvrn with the dev configuration"
const StagingName = "staging"
const StagingAlias = "s"
const StagingUsage = "specify to run wyvrn with the staging configuration"
const ProdName = "prod"
const ProdAlias = "p"
const ProdUsage = "specify to run wyvrn with the staging configuration"
