package constants

const ModuleName = "module"
const ModuleAlias = "m"
const ModuleUsage = "signal cli to create a template for a WASM module; value will be used to name the module"
const LanguageName = "language"
const LanguageAlias = "l"
const LanguageUsage = "the language you want to create your new wyvrn app/module for; apps can run modules compiled from multiple languages, but needs a language to make the first module with"
const DirectoryName = "dir"
const DirectoryAlias = "d"
const DirectoryUsage = "specify the directory to create your new wyvrn app/module; defaults to the current directory"
const StepName = "step"
const StepAlias = "s"
const StepUsage = "specify the name of the (first) step in your module"
const NameName = "name"
const NameAlias = "n"
const NameUsage = "name your new wyvrn app"
const ConfigName = "config"
const ConfigAlias = "c"
const ConfigUsage = "use to create a new config, must be used in unison with -e|--env flag"
const EnvName = "env"
const EnvAlias = "e"
const EnvUsage = `if using with run command, specifies the environment to run; 
if using with new command, specifies which environment you want to create a new config for`
const DevEnv = "dev"
const StageEnv = "Staging"
const ProdEnv = "prod"
